# Generated by Django 3.2.4 on 2021-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=240, verbose_name='Evento a recordar')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
