# Generated by Django 3.2.4 on 2021-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionavisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=240, verbose_name='Evento a recordar')),
                ('fecha', models.DateField()),
                ('email_remitente', models.EmailField(max_length=254)),
                ('email_destinatario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
